### ISSUE TITLE
Unexptected exception while parsing console command

### ISSUE THREAD

**Issue by TheColin21** [Yey007/Paper-Auto-Updater#2]
[10:37:37 WARN]: Unexpected exception while parsing console command "paperautoupdate update"
org.bukkit.command.CommandException: Unhandled exception executing command 'paperautoupdate' in plugin paperautoupdate v1.2.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-318]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[patched_1.15.2.jar:git-Paper-318]
        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469) ~[patched_1.15.2.jar:git-Paper-318]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-318]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-318]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at io.github.yey007.paperautoupdate.Updater.onCommand(Main.java:264) ~[?:?]
        at io.github.yey007.paperautoupdate.CommandHandler.onCommand(Main.java:121) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-318]
        ... 8 more

**Comment by TheColin21** [comment]
Same happens when using "pau update"

**Comment by utkudotdev** [comment]
Hey, Sorry I'm so late to respond. I fixed the issue in the newest build
